siteweather/authentication/urls.py
from django.urls import path, include

from .views import *


registration_urls = ([
    path('login/', UserLoginFormView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('register/', RegisterFormView.as_view(), name='register'),
], 'auth')

urlpatterns = [
    path('auth/', include(registration_urls)),
]

siteweather/profile/urls.py
from django.urls import path, include

from .views import *


profile_urls = ([
    path('<int:pk>/', UserProfile.as_view(), name='profile',),
    path('update/', UserProfileUpdate.as_view(), name='profile_update'),
    path('password_update/', UserPasswordUpdate.as_view(), name='password_update'),
], 'profile')

urlpatterns = [
    path('profile/', include(profile_urls)),
]

siteweather/urls.py
from django.urls import path, include

from .views import *

app_name = 'siteweather'

siteweather_urls = [
    path('', Home.as_view(), name='home'),
    path('<int:pk>/', ViewCity.as_view(), name='view_city'),
    path('city_block/<int:pk>/', DeleteCityBlock.as_view(), name='delete'),
    path('find_by/', FindCity.as_view(), name='find_by'),
    path('registered_users/', UsersList.as_view(), name='users_list'),
    path('site_settings/', PersonalSiteSettingsAPIView.as_view(), name='site_settings'),
]

urlpatterns = [
    path('', include('siteweather.authentication.urls')),
    path('', include('siteweather.profile.urls')),
    path('siteweather/', include(siteweather_urls)),
]

task/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from siteweather.views import schema_view
from task import settings
from siteweather.authentication.views import AdminLogoutView


urlpatterns = [
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('docs/', schema_view, name="docs"),
    path('admin/logout/', AdminLogoutView.as_view()),
    path('admin/', admin.site.urls),
    path('', include('siteweather.urls', namespace='siteweather')),
    path('api-auth/', include('rest_framework.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

siteweather/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse
from django.utils.html import format_html
from django.contrib.postgres.fields import ArrayField

ROLE_CHOICES = (
    ('Standard', 'Standard'),
    ('Premium', 'Premium'),
)


class CustomUser(AbstractUser):
    photo = models.ImageField(null=True, blank=True, upload_to='users/%Y/%m/%d')
    phone_number = models.CharField(verbose_name='Phone number', max_length=15, blank=True)
    user_city = models.CharField(verbose_name='City', max_length=50, blank=True)
    date_of_birth = models.DateField(verbose_name='Date of birth', null=True, blank=False)
    role = models.CharField(max_length=100, choices=ROLE_CHOICES, default='Standard', verbose_name='Role')

    def colored_premium(self):
        if self.role == 'Premium':
            return format_html(f'<span style="color: #FFBD1B;"><strong>{self.role}</strong></span>')
        else:
            return self.role

    colored_premium.short_description = 'Role'
    colored_premium.admin_order_field = 'role'

    def get_absolute_url(self):
        return reverse('siteweather:profile', kwargs={'pk': self.pk})

    def __str__(self):
        return self.username

    class Meta:
        verbose_name = 'User'
        verbose_name_plural = 'Users'
        ordering = ['username']


class WeatherDescription(models.Model):
    short_description = models.CharField(verbose_name='Main description', max_length=300, blank=True)
    full_description = models.CharField(verbose_name='Full description', max_length=300, blank=True)
    weather_icon = models.CharField(verbose_name='Icon', max_length=300, default='01d', blank=True, unique=True,
                                    primary_key=True)


class Location(models.Model):
    city_name = models.CharField(verbose_name='Name of city', max_length=300, unique=True, primary_key=True)
    country = models.CharField(verbose_name='Country', max_length=300, default='Unknown', blank=True)


class CityBlock(models.Model):
    location = models.ForeignKey(Location, on_delete=models.DO_NOTHING, blank=True, null=True)
    weather_description = models.ForeignKey(WeatherDescription, on_delete=models.DO_NOTHING, blank=True, null=True)
    timestamp = models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')
    temperature = models.IntegerField(verbose_name='Temperature', default=0, blank=True)
    humidity = models.IntegerField(verbose_name='Humidity', default=0, blank=True)
    pressure = models.IntegerField(verbose_name='Pressure', default=0, blank=True)
    wind_speed = models.IntegerField(verbose_name='Wind speed', default=0, blank=True)
    searched_by_user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, blank=True, null=True)

    def get_absolute_url(self):
        return reverse('siteweather:view_city', kwargs={'pk': self.pk})

    def __str__(self):
        return self.location.city_name

    class Meta:
        verbose_name = 'City'
        verbose_name_plural = 'Cities'
        ordering = ['-timestamp']
        permissions = [
            ('see_users', 'Ability to see users from specific city in city block'),
        ]

siteweather/authentication/forms.py
import re

import requests
from django import forms
from django.contrib.auth import authenticate

from siteweather.models import CustomUser
from task import settings


class BaseCustomUserForm(forms.Form):
    first_name = forms.CharField(max_length=300, label='first_name', widget=forms.TextInput(
        attrs={'class': 'form-control'}))
    last_name = forms.CharField(max_length=300, label='last_name', widget=forms.TextInput(
        attrs={'class': 'form-control'}))
    email = forms.EmailField(label='email_field', widget=forms.EmailInput(
        attrs={'class': 'form-control'}), required=True)
    phone_number = forms.CharField(label='phone_number', max_length=15, widget=forms.TextInput(
        attrs={'class': 'form-control'}), required=False)
    city_name = forms.CharField(max_length=300, label='city_name', widget=forms.TextInput(
        attrs={'class': 'form-control'}))

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super().__init__(*args, **kwargs)

    def clean_first_name(self):
        first_name = self.cleaned_data['first_name']
        if len(first_name) < 2:
            self.add_error('first_name', 'First name is too short')
        return first_name

    def clean_last_name(self):
        last_name = self.cleaned_data['last_name']
        if len(last_name) < 2:
            self.add_error('last_name', 'Surname is too short')
        return last_name

    def clean_phone_number(self):
        phone_number = self.cleaned_data['phone_number']
        if phone_number:
            letters_check = phone_number[1:].isdecimal()
            symbols_check = re.search(r'\W', phone_number[1:])
            plus_check = re.search(r'\W', phone_number[0])
            if plus_check is not None and symbols_check is None and letters_check is True:
                if phone_number[0] != '+':
                    self.add_error('phone_number', "Only '+' is allowed at the beginning")
            if letters_check is False or symbols_check is not None:
                self.add_error('phone_number', 'Only numbers are allowed')
        return phone_number

    def clean_email(self):
        email = self.cleaned_data['email']
        if not self.user.is_anonymous:
            if self.user.email != email:
                if CustomUser.objects.filter(email=email).exists():
                    self.add_error('email', 'User with entered email exists')
        else:
            if CustomUser.objects.filter(email=email).exists():
                self.add_error('email', 'User with entered email exists')
        return email

    def clean_city_name(self):
        city_name = self.cleaned_data['city_name']
        url = f'{settings.SITE_WEATHER_URL}?q={city_name}&appid={settings.APP_ID}&units=metric'
        r = requests.get(url).json()
        if r['cod'] == '404':
            self.add_error('city_name', f'City was not found')
        return city_name


class UserRegisterForm(BaseCustomUserForm):
    username = forms.CharField(max_length=300, label='login', widget=forms.TextInput(
        attrs={'class': 'form-control'}))
    password = forms.CharField(max_length=300, label='password', widget=forms.PasswordInput(
        attrs={'class': 'form-control'}))
    password2 = forms.CharField(max_length=300, label='password2', widget=forms.PasswordInput(
        attrs={'class': 'form-control'}))

    def clean_password2(self):
        data = self.cleaned_data
        if data['password'] != data['password2']:
            self.add_error('password2', 'The verification password does not match the entered one')
        return data

    def clean_username(self):
        username = self.cleaned_data['username']
        if len(username) < 4:
            self.add_error('username', 'Your username has to contain at least 4 symbols')
        if ' ' in str(username):
            self.add_error('username', 'No spaces allowed')
        check_username = CustomUser.objects.filter(username=username).exists()
        if check_username:
            self.add_error('username', 'Username is taken')
        return username


class UserLoginForm(UserRegisterForm):
    email = None
    password2 = None
    phone_number = None
    first_name = None
    last_name = None
    city_name = None

    def clean_username(self):
        return self.cleaned_data['username']

    def clean(self):
        data = self.cleaned_data
        username = data['username']
        password = data['password']
        user = authenticate(username=username, password=password)
        if user is None:
            self.add_error('password', 'Wrong username or password')
        return data

siteweather/authentication/views.py
import logging

from django.contrib.auth import login, logout
from django.contrib.auth.models import Group
from django.shortcuts import redirect, render
from rest_framework import status
from rest_framework.generics import CreateAPIView, GenericAPIView
from rest_framework.parsers import FormParser, MultiPartParser
from rest_framework.renderers import JSONRenderer, TemplateHTMLRenderer
from rest_framework.response import Response
from rest_framework.views import APIView

from siteweather.authentication.forms import *
from siteweather.authentication.serializers import LoginSerializer
from siteweather.serializers import RegistrationSerializer

logger = logging.getLogger('django')


class RegisterFormView(CreateAPIView):
    serializer_class = RegistrationSerializer
    template_name = 'authentication/registration.html'
    form_class = UserRegisterForm
    renderer_classes = [JSONRenderer, TemplateHTMLRenderer]
    parser_classes = (MultiPartParser, FormParser)
    pagination_class = None

    def get(self, request, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect('siteweather:profile:profile', pk=self.request.user.pk)
        form = self.form_class(request.user)
        return render(request, self.template_name, {'form': form})

    def create(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        if serializer.is_valid():
            self.perform_create(serializer)
            return redirect('siteweather:profile:profile', pk=self.request.user.pk)
        else:
            return Response({
                'errors': serializer.errors,
                'data': serializer.data,
            }, status=status.HTTP_406_NOT_ACCEPTABLE)

    def perform_create(self, serializer):
        user = CustomUser.objects.create_user(**serializer.data, role='Standard')
        group = Group.objects.get(name='Registered')
        user.groups.add(group)
        base_permissions = group.permissions.all()
        user.user_permissions.set(base_permissions)
        login(self.request, user)


class UserLoginFormView(GenericAPIView):
    serializer_class = LoginSerializer
    renderer_classes = [JSONRenderer, TemplateHTMLRenderer]
    parser_classes = (MultiPartParser, FormParser)
    template_name = 'authentication/login.html'
    form_class = UserLoginForm

    def get(self, request, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect('siteweather:profile:profile', pk=self.request.user.pk)
        form = self.form_class(request.user)
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        serializer = LoginSerializer(data={'username': request.data['username'],
                                           'password': request.data['password']})
        if serializer.is_valid():
            user = serializer.validated_data['password']
            login(request, user)
            return redirect('siteweather:profile:profile', user.pk)
        else:
            user = CustomUser.objects.filter(username__exact=serializer.data['username']).exists()
            if user:
                logger.warning(f"Unsuccessful authorization into {serializer.data['username']}")
            return Response({
                'errors': serializer.errors,
                'data': serializer.data,
                }, template_name=self.template_name, status=status.HTTP_406_NOT_ACCEPTABLE)


class UserLogoutView(APIView):
    url = 'siteweather:home'

    def post(self, request, *args, **kwargs):
        if self.request.user.is_anonymous:
            return redirect('siteweather:auth:login')
        timezone = request.session.get('django_timezone')
        logger.info(f"{self.request.user.username} logged out")
        logout(request)
        request.session['django_timezone'] = timezone
        return redirect(self.url)


class AdminLogoutView(UserLogoutView):
    url = '/admin/'

    def get(self, request, *args, **kwargs):
        return super().post(request, *args, **kwargs)

siteweather/profile/views.py
import logging

from rest_framework import status
from rest_framework.generics import RetrieveAPIView, GenericAPIView
from rest_framework.parsers import MultiPartParser, FormParser
from rest_framework.renderers import TemplateHTMLRenderer, JSONRenderer
from rest_framework.response import Response

from siteweather.models import CustomUser
from siteweather.profile.serializers import SuperUserCustomUserSerializer, UpdateProfileSerializer, \
    UpdatePasswordSerializer
from siteweather.serializers import CustomUserSerializer

logger = logging.getLogger('django')


class UserProfile(RetrieveAPIView):
    queryset = CustomUser.objects.all()
    renderer_classes = [JSONRenderer, TemplateHTMLRenderer]
    parser_classes = (MultiPartParser, FormParser)
    template_name = 'profile/profile.html'

    def get(self, request, *args, **kwargs):
        profile = self.get_object()
        serialized = self.get_serializer(profile).data
        return Response({'profile': serialized}, template_name='profile/profile.html')

    def get_serializer_class(self):
        if self.request.user.is_superuser:
            return SuperUserCustomUserSerializer
        else:
            return CustomUserSerializer


class UserProfileUpdate(GenericAPIView):
    serializer_class = UpdateProfileSerializer
    renderer_classes = [JSONRenderer, TemplateHTMLRenderer]
    template_name = 'profile/profile_update.html'
    parser_classes = (MultiPartParser, FormParser)

    def get_object(self):
        return CustomUser.objects.get(pk=self.request.user.pk)

    def get(self, request, *args, **kwargs):
        user = CustomUser.objects.get(pk=self.request.user.pk)
        serializer = UpdateProfileSerializer(user)
        return Response(serializer.data)

    def patch(self, request, *args, **kwargs):
        partial = kwargs.pop('partial', False)
        serializer = self.serializer_class(self.request.user, data=request.data, partial=partial)
        if serializer.is_valid():
            self.perform_update(serializer)
            return Response({'message': 'You have successfully updated your profile', 'data': serializer.data},
                            status=status.HTTP_200_OK)
        else:
            return Response({'errors': serializer.errors}, template_name=self.template_name,
                            status=status.HTTP_406_NOT_ACCEPTABLE)

    def perform_update(self, serializer):
        serializer.save(self.request)


class UserPasswordUpdate(GenericAPIView):
    serializer_class = UpdatePasswordSerializer
    renderer_classes = [JSONRenderer, TemplateHTMLRenderer]
    parser_classes = [MultiPartParser, FormParser]
    template_name = 'profile/password_update.html'

    def get(self, request, *args, **kwargs):
        user = CustomUser.objects.get(pk=self.request.user.pk)
        serializer = UpdatePasswordSerializer(user)
        return Response(serializer.data)

    def patch(self, request, *args, **kwargs):
        partial = kwargs.pop('partial', False)
        serializer = UpdatePasswordSerializer(self.request.user, data=request.data, partial=partial)
        if serializer.is_valid():
            self.perform_update(serializer)
            logger.warning(f'{self.request.user} updated his password')
            return Response({'message': 'Your password has been successfully updated'}, status=status.HTTP_200_OK)
        else:
            return Response({'errors': serializer.errors}, template_name=self.template_name,
                            status=status.HTTP_406_NOT_ACCEPTABLE)

    def get_object(self):
        return CustomUser.objects.get(pk=self.request.user.pk)

    def perform_update(self, serializer):
        serializer.save(self.request)

siteweather/templates/profile/password_update.html
{% extends 'base.html' %}

{% block title %}
  {{ user.first_name }} {{ user.last_name }}
{% endblock %}

{% block sidebar %}
  {% include 'inc/_sidebar.html' %}
{% endblock %}

{% block content %}
  {% if request.user.is_authenticated %}
    <form id="password-update-form" autocomplete="off" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="card mb-4">
        <div class="card-header">
          <h5>
            <strong>
              {{ user.first_name }} {{ user.last_name }}
            </strong>
          </h5>
          {{ user.username }}
        </div>
        <div class="card-body">
          <div class="media">
            <div class="media-body">
              <h6 class="card-text">
                <label for="id_password">
                  Password:
                  <input type="password" class="form-control" name="password" required="">
                </label>
                <label for="id_password2">
                  <h6>Repeat password:</h6>
                  <input type="password" class="form-control" name="password2">
                  {% if errors %}
                    {% for error in errors.password2 %}
                      <br>
                      <div class="alert alert-danger">
                        <strong>{{ error|escape }}</strong>
                      </div>
                    {% endfor %}
                  {% endif %}
                </label>
              </h6>
              <button type="submit" class="btn-outline-primary btn btn-block">
                Update
              </button>
            </div>
          </div>
        </div>
        <div class="card-footer text-muted">
          <a href="{% url 'siteweather:profile:profile_update' %}">Back to editing</a>
        </div>
      </div>
    </form>
  {% else %}
    <div class="btn btn-block disabled btn-danger">
      <strong>
        You are not authorized to view this page.
      </strong>
    </div>
  {% endif %}
{% endblock %}

{% block time %}
  {% include 'inc/_time.html' %}
{% endblock %}

{% block javascript %}
  <script>
    $(document).ready(function () {
      let token = '{{ csrf_token }}';
      $("#password-update-form").submit(function (event) {
        event.preventDefault();
        let serializerData = $(this).serialize();
        $.ajax({
          type: 'PATCH',
          data: serializerData,
          headers: {"X-CSRFToken": token},
          async: false,
          success: function (response) {
            location.href = '{% url 'siteweather:profile:profile' pk %}';
            alert(response.message);
          },
          error: function (response) {
            alert(response["responseJSON"]["error"]);
          }
        })
      })
    })
  </script>
{% endblock %}

siteweather/templates/profile/profile.html
{% extends 'base.html' %}
{% load tz %}

{% block title %}
  {{ profile.first_name }} {{ profile.last_name }}
{% endblock %}

{% block sidebar %}
  {% include 'inc/_sidebar.html' %}
{% endblock %}

{% block content %}
  <div class="card mb-4">
    <div class="card-header">
      <h5>
        <strong>
          {{ profile.first_name }} {{ profile.last_name }}
        </strong>
      </h5>
      {{ profile.age }} y.o.
    </div>
    <div class="card-body">
      <div class="media">
        <div class="media-body">
          <h6 class="card-text">
            Username – {{ profile.username }} <br>
            {% if profile.email %}
              Email – {{ profile.email }} <br>
            {% endif %}
            Date of birth – {{ profile.date_of_birth }} <br>
            {% if profile.phone_number %}
              Phone number – {{ profile.phone_number }} <br>
            {% endif %}
            City - {{ profile.user_city }} <br>
            {% if profile.photo %}
              <img src="{{ profile.photo }}" width="100%" alt="profile_photo" class="img-thumbnail">
            {% endif %}
          </h6>
        </div>
      </div>
    </div>
    <div class="card-footer text-muted">
      <strong>
        {% if profile.email == user.email %}
          <a href="{% url 'siteweather:profile:profile_update' %}">Edit profile</a> <br>
        {% endif %}
      </strong>
      {% if profile.is_registered_recently %}
        <strong>
          Registered recently
        </strong>
      {% endif %}
    </div>
  </div>
{% endblock %}

{% block time %}
  {% include 'inc/_time.html' %}
{% endblock %}

siteweather/templates/profile/profile_update.html
{% extends 'base.html' %}
{% load siteweather_extras %}

{% block title %}
  {{ user.first_name }} {{ user.last_name }}
{% endblock %}

{% block sidebar %}
  {% include 'inc/_sidebar.html' %}
{% endblock %}

{% block content %}
  {% if request.user.is_authenticated %}
    <div class="card mb-4">
      <form id="profile-update-form" autocomplete="off" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="card-header">
          <h5>
            <strong>
              {{ user.first_name }} {{ user.last_name }}
            </strong>
          </h5>
          {{ user.username }}
        </div>
        <div class="card-body">
          <div class="media">
            <div class="media-body">
              <h6 class="card-text">
                <label for="id_first_name">
                  <h6>First name:</h6>
                  <input type="text" class="form-control" name="first_name"
                         value="{{ user.first_name }}" required="" id="id_first_name">
                  {% if errors %}
                    {% for error in errors.first_name %}
                      <br>
                      <div class="alert alert-danger">
                        <strong>{{ error|escape }}</strong>
                      </div>
                    {% endfor %}
                  {% endif %}
                </label>
                <label for="id_last_name">
                  <h6>Last name:</h6>
                  <input type="text" class="form-control" name="last_name"
                         value="{{ user.last_name }}">
                  {% if errors %}
                    {% for error in errors.last_name %}
                      <br>
                      <div class="alert alert-danger">
                        <strong>{{ error|escape }}</strong>
                      </div>
                    {% endfor %}
                  {% endif %}
                </label>
                <label for="id_email">
                  <h6>Email:</h6>
                  <input type="text" class="form-control" name="email"
                         value="{{ user.email }}">
                  {% if errors %}
                    {% for error in errors.email %}
                      <br>
                      <div class="alert alert-danger">
                        <strong>{{ error|escape }}</strong>
                      </div>
                    {% endfor %}
                  {% endif %}
                </label>
                <label for="id_user_city">
                  <h6>City:</h6>
                  <input type="text" class="form-control" name="user_city"
                         value="{{ user.user_city }}">
                  {% if errors %}
                    {% for error in errors.user_city %}
                      <br>
                      <div class="alert alert-danger">
                        <strong>{{ error|escape }}</strong>
                      </div>
                    {% endfor %}
                  {% endif %}
                </label>
                <label for="id_date_of_birth">
                  Date of birth:
                  <input type="date" class="form-control" name="date_of_birth"
                         value="{{ user.date_of_birth|parse_date_to_string }}" required="" id="id_date_of_birth"
                         max="{% now 'Y-m-d' %}">
                </label>
                {% if errors %}
                  {% for error in errors.date_of_birth %}
                    <div class="alert alert-danger">
                      <strong>{{ error|escape }}</strong>
                    </div>
                  {% endfor %}
                {% endif %}
                <label for="id_phone_number">
                  <h6>Phone number:</h6>
                  <input type="text" class="form-control" name="phone_number"
                         value="{{ user.phone_number }}">
                  {% if errors %}
                    {% for error in errors.phone_number %}
                      <br>
                      <div class="alert alert-danger">
                        <strong>{{ error|escape }}</strong>
                      </div>
                    {% endfor %}
                  {% endif %}
                </label>
                <label for="id_photo">
                  <h6>Photo:</h6>
                  {% if user.photo %}
                    currently: <img src="{{ user.photo.url }}" width=100% alt="profile_photo" class="img-thumbnail">
                  {% endif %}
                  <input type="checkbox" name="photo-clear" id="photo-clear_id">
                  <label for="photo-clear_id">Clear</label><br>
                  Change:
                  <input type="file" name="photo" accept="image/*" id="id_photo">
                  {% if errors %}
                    {% for error in errors.photo %}
                      <br>
                      <div class="alert alert-danger">
                        <strong>{{ error|escape }}</strong>
                      </div>
                    {% endfor %}
                  {% endif %}
                </label>
              </h6>
              <button type="submit" class="btn-outline-primary btn btn-block">
                Update
              </button>
            </div>
          </div>
        </div>
      </form>
      <div class="card-footer text-muted">
        <strong>
          <a href="{% url 'siteweather:profile:password_update' %}">Change password</a>
        </strong>
      </div>
    </div>
  {% else %}
    <div class="btn btn-block disabled btn-danger">
      <strong>
        You are not authorized to view this page.
      </strong>
    </div>
  {% endif %}
{% endblock %}

{% block time %}
  {% include 'inc/_time.html' %}
{% endblock %}

{% block javascript %}
  <script>
    $(document).ready(function () {
      let token = '{{ csrf_token }}';
      $("#profile-update-form").submit(function (event) {
        event.preventDefault();
        let form_data = new FormData($("#profile-update-form")[0]);
        form_data.append('file', $('input[type=file]')[0].files[0]);
        $.ajax({
          type: 'PATCH',
          data: form_data,
          headers: {"X-CSRFToken": token},
          processData: false,
          contentType: false,
          success: function () {
            location.href = '{% url 'siteweather:profile:profile' user.pk %}';
          },
          error: function (response) {
            for (el in response["responseJSON"]["errors"]){alert(response["responseJSON"]["errors"][el])}
          }
        })
      })
    })
  </script>
{% endblock %}