siteweather/authentication/urls.py
from django.urls import path, include

from .views import *


registration_urls = ([
    path('login/', UserLoginFormView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('register/', RegisterFormView.as_view(), name='register'),
], 'auth')

urlpatterns = [
    path('auth/', include(registration_urls)),
]

siteweather/profile/urls.py
from django.urls import path, include

from .views import *


profile_urls = ([
    path('<int:pk>/', UserProfile.as_view(), name='profile',),
    path('update/', UserProfileUpdate.as_view(), name='profile_update'),
    path('password_update/', UserPasswordUpdate.as_view(), name='password_update'),
], 'profile')

urlpatterns = [
    path('profile/', include(profile_urls)),
]

siteweather/urls.py
from django.urls import path, include

from .views import *

app_name = 'siteweather'

siteweather_urls = [
    path('', Home.as_view(), name='home'),
    path('<int:pk>/', ViewCity.as_view(), name='view_city'),
    path('city_block/<int:pk>/', DeleteCityBlock.as_view(), name='delete'),
    path('find_by/', FindCity.as_view(), name='find_by'),
    path('registered_users/', UsersList.as_view(), name='users_list'),
    path('site_settings/', PersonalSiteSettingsAPIView.as_view(), name='site_settings'),
]

urlpatterns = [
    path('', include('siteweather.authentication.urls')),
    path('', include('siteweather.profile.urls')),
    path('siteweather/', include(siteweather_urls)),
]

task/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from siteweather.views import schema_view
from task import settings
from siteweather.authentication.views import AdminLogoutView


urlpatterns = [
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('docs/', schema_view, name="docs"),
    path('admin/logout/', AdminLogoutView.as_view()),
    path('admin/', admin.site.urls),
    path('', include('siteweather.urls', namespace='siteweather')),
    path('api-auth/', include('rest_framework.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

siteweather/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse
from django.utils.html import format_html
from django.contrib.postgres.fields import ArrayField

ROLE_CHOICES = (
    ('Standard', 'Standard'),
    ('Premium', 'Premium'),
)


class CustomUser(AbstractUser):
    photo = models.ImageField(null=True, blank=True, upload_to='users/%Y/%m/%d')
    phone_number = models.CharField(verbose_name='Phone number', max_length=15, blank=True)
    user_city = models.CharField(verbose_name='City', max_length=50, blank=True)
    date_of_birth = models.DateField(verbose_name='Date of birth', null=True, blank=False)
    role = models.CharField(max_length=100, choices=ROLE_CHOICES, default='Standard', verbose_name='Role')

    def colored_premium(self):
        if self.role == 'Premium':
            return format_html(f'<span style="color: #FFBD1B;"><strong>{self.role}</strong></span>')
        else:
            return self.role

    colored_premium.short_description = 'Role'
    colored_premium.admin_order_field = 'role'

    def get_absolute_url(self):
        return reverse('siteweather:profile', kwargs={'pk': self.pk})

    def __str__(self):
        return self.username

    class Meta:
        verbose_name = 'User'
        verbose_name_plural = 'Users'
        ordering = ['username']


class WeatherDescription(models.Model):
    short_description = models.CharField(verbose_name='Main description', max_length=300, blank=True)
    full_description = models.CharField(verbose_name='Full description', max_length=300, blank=True)
    weather_icon = models.CharField(verbose_name='Icon', max_length=300, default='01d', blank=True, unique=True,
                                    primary_key=True)


class Location(models.Model):
    city_name = models.CharField(verbose_name='Name of city', max_length=300, unique=True, primary_key=True)
    country = models.CharField(verbose_name='Country', max_length=300, default='Unknown', blank=True)


class CityBlock(models.Model):
    location = models.ForeignKey(Location, on_delete=models.DO_NOTHING, blank=True, null=True)
    weather_description = models.ForeignKey(WeatherDescription, on_delete=models.DO_NOTHING, blank=True, null=True)
    timestamp = models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')
    temperature = models.IntegerField(verbose_name='Temperature', default=0, blank=True)
    humidity = models.IntegerField(verbose_name='Humidity', default=0, blank=True)
    pressure = models.IntegerField(verbose_name='Pressure', default=0, blank=True)
    wind_speed = models.IntegerField(verbose_name='Wind speed', default=0, blank=True)
    searched_by_user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, blank=True, null=True)

    def get_absolute_url(self):
        return reverse('siteweather:view_city', kwargs={'pk': self.pk})

    def __str__(self):
        return self.location.city_name

    class Meta:
        verbose_name = 'City'
        verbose_name_plural = 'Cities'
        ordering = ['-timestamp']
        permissions = [
            ('see_users', 'Ability to see users from specific city in city block'),
        ]

siteweather/admin_panel/forms.py
from django import forms
from django.contrib.admin.widgets import FilteredSelectMultiple
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth.models import Group
from django.utils.timezone import localtime

from siteweather.models import CustomUser


class CustomUserAdminForm(UserChangeForm):
    def clean_username(self):
        username = self.cleaned_data['username']
        if len(username) < 4:
            raise forms.ValidationError('Your username has to contain at least 4 symbols')
        else:
            return username

    def clean_date_of_birth(self):
        date_of_birth = self.cleaned_data['date_of_birth']
        today = localtime().date()
        if date_of_birth > today.today():
            raise forms.ValidationError('You cannot provide a date of birth from the future')
        return date_of_birth


class GroupAdminForm(forms.ModelForm):
    class Meta:
        model = Group
        exclude = []

    users = forms.ModelMultipleChoiceField(
        queryset=CustomUser.objects.all(),
        required=False,
        widget=FilteredSelectMultiple('users', False)
    )

    def __init__(self, *args, **kwargs):
        super(GroupAdminForm, self).__init__(*args, **kwargs)
        if self.instance.pk:
            self.fields['users'].initial = self.instance.user_set.all()

    def save_m2m(self):
        self.instance.user_set.set(self.cleaned_data['users'])

    def save(self, *args, **kwargs):
        instance = super(GroupAdminForm, self).save()
        self.save_m2m()
        return instance

siteweather/forms.py
import logging

from django import forms

from siteweather.authentication.forms import BaseCustomUserForm

logger = logging.getLogger('django')


class CityBlockForm(BaseCustomUserForm):
    first_name = None
    last_name = None
    email = None
    phone_number = None


class CityBlockFilterForm(forms.Form):
    city_name_filter = forms.CharField(max_length=300, label='city_name_filter', widget=forms.TextInput(
        attrs={'class': 'form-control'}), )
    date_filter = forms.DateField(label='date_filter', widget=forms.DateInput(
        attrs={'class': 'form-control'}), )

siteweather/authentication/views.py
import logging

from django.contrib.auth import login, logout
from django.contrib.auth.models import Group
from django.shortcuts import redirect, render
from rest_framework import status
from rest_framework.generics import CreateAPIView, GenericAPIView
from rest_framework.parsers import FormParser, MultiPartParser
from rest_framework.renderers import JSONRenderer, TemplateHTMLRenderer
from rest_framework.response import Response
from rest_framework.views import APIView

from siteweather.authentication.forms import *
from siteweather.authentication.serializers import LoginSerializer
from siteweather.serializers import RegistrationSerializer

logger = logging.getLogger('django')


class RegisterFormView(CreateAPIView):
    serializer_class = RegistrationSerializer
    template_name = 'authentication/registration.html'
    form_class = UserRegisterForm
    renderer_classes = [JSONRenderer, TemplateHTMLRenderer]
    parser_classes = (MultiPartParser, FormParser)
    pagination_class = None

    def get(self, request, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect('siteweather:profile:profile', pk=self.request.user.pk)
        form = self.form_class(request.user)
        return render(request, self.template_name, {'form': form})

    def create(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        if serializer.is_valid():
            self.perform_create(serializer)
            return redirect('siteweather:profile:profile', pk=self.request.user.pk)
        else:
            return Response({
                'errors': serializer.errors,
                'data': serializer.data,
            }, status=status.HTTP_406_NOT_ACCEPTABLE)

    def perform_create(self, serializer):
        user = CustomUser.objects.create_user(**serializer.data, role='Standard')
        group = Group.objects.get(name='Registered')
        user.groups.add(group)
        base_permissions = group.permissions.all()
        user.user_permissions.set(base_permissions)
        login(self.request, user)


class UserLoginFormView(GenericAPIView):
    serializer_class = LoginSerializer
    renderer_classes = [JSONRenderer, TemplateHTMLRenderer]
    parser_classes = (MultiPartParser, FormParser)
    template_name = 'authentication/login.html'
    form_class = UserLoginForm

    def get(self, request, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect('siteweather:profile:profile', pk=self.request.user.pk)
        form = self.form_class(request.user)
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        serializer = LoginSerializer(data={'username': request.data['username'],
                                           'password': request.data['password']})
        if serializer.is_valid():
            user = serializer.validated_data['password']
            login(request, user)
            return redirect('siteweather:profile:profile', user.pk)
        else:
            user = CustomUser.objects.filter(username__exact=serializer.data['username']).exists()
            if user:
                logger.warning(f"Unsuccessful authorization into {serializer.data['username']}")
            return Response({
                'errors': serializer.errors,
                'data': serializer.data,
                }, template_name=self.template_name, status=status.HTTP_406_NOT_ACCEPTABLE)


class UserLogoutView(APIView):
    url = 'siteweather:home'

    def post(self, request, *args, **kwargs):
        if self.request.user.is_anonymous:
            return redirect('siteweather:auth:login')
        timezone = request.session.get('django_timezone')
        logger.info(f"{self.request.user.username} logged out")
        logout(request)
        request.session['django_timezone'] = timezone
        return redirect(self.url)


class AdminLogoutView(UserLogoutView):
    url = '/admin/'

    def get(self, request, *args, **kwargs):
        return super().post(request, *args, **kwargs)

siteweather/profile/views.py
import logging

from rest_framework import status
from rest_framework.generics import RetrieveAPIView, GenericAPIView
from rest_framework.parsers import MultiPartParser, FormParser
from rest_framework.renderers import TemplateHTMLRenderer, JSONRenderer
from rest_framework.response import Response

from siteweather.models import CustomUser
from siteweather.profile.serializers import SuperUserCustomUserSerializer, UpdateProfileSerializer, \
    UpdatePasswordSerializer
from siteweather.serializers import CustomUserSerializer

logger = logging.getLogger('django')


class UserProfile(RetrieveAPIView):
    queryset = CustomUser.objects.all()
    renderer_classes = [JSONRenderer, TemplateHTMLRenderer]
    parser_classes = (MultiPartParser, FormParser)
    template_name = 'profile/profile.html'

    def get(self, request, *args, **kwargs):
        profile = self.get_object()
        serialized = self.get_serializer(profile).data
        return Response({'profile': serialized}, template_name='profile/profile.html')

    def get_serializer_class(self):
        if self.request.user.is_superuser:
            return SuperUserCustomUserSerializer
        else:
            return CustomUserSerializer


class UserProfileUpdate(GenericAPIView):
    serializer_class = UpdateProfileSerializer
    renderer_classes = [JSONRenderer, TemplateHTMLRenderer]
    template_name = 'profile/profile_update.html'
    parser_classes = (MultiPartParser, FormParser)

    def get_object(self):
        return CustomUser.objects.get(pk=self.request.user.pk)

    def get(self, request, *args, **kwargs):
        user = CustomUser.objects.get(pk=self.request.user.pk)
        serializer = UpdateProfileSerializer(user)
        return Response(serializer.data)

    def patch(self, request, *args, **kwargs):
        partial = kwargs.pop('partial', False)
        serializer = self.serializer_class(self.request.user, data=request.data, partial=partial)
        if serializer.is_valid():
            self.perform_update(serializer)
            return Response({'message': 'You have successfully updated your profile', 'data': serializer.data},
                            status=status.HTTP_200_OK)
        else:
            return Response({'errors': serializer.errors}, template_name=self.template_name,
                            status=status.HTTP_406_NOT_ACCEPTABLE)

    def perform_update(self, serializer):
        serializer.save(self.request)


class UserPasswordUpdate(GenericAPIView):
    serializer_class = UpdatePasswordSerializer
    renderer_classes = [JSONRenderer, TemplateHTMLRenderer]
    parser_classes = [MultiPartParser, FormParser]
    template_name = 'profile/password_update.html'

    def get(self, request, *args, **kwargs):
        user = CustomUser.objects.get(pk=self.request.user.pk)
        serializer = UpdatePasswordSerializer(user)
        return Response(serializer.data)

    def patch(self, request, *args, **kwargs):
        partial = kwargs.pop('partial', False)
        serializer = UpdatePasswordSerializer(self.request.user, data=request.data, partial=partial)
        if serializer.is_valid():
            self.perform_update(serializer)
            logger.warning(f'{self.request.user} updated his password')
            return Response({'message': 'Your password has been successfully updated'}, status=status.HTTP_200_OK)
        else:
            return Response({'errors': serializer.errors}, template_name=self.template_name,
                            status=status.HTTP_406_NOT_ACCEPTABLE)

    def get_object(self):
        return CustomUser.objects.get(pk=self.request.user.pk)

    def perform_update(self, serializer):
        serializer.save(self.request)

siteweather/templates/siteweather/cityblock_detail.html
{% extends 'base.html' %}
{% load siteweather_extras %}


{% block title %}
  {{ city_item.location.city_name }} | {{ city_item.timestamp|parse_time|date:'m-d-Y' }}
{% endblock %}

{% block sidebar %}
  {% include 'inc/_sidebar.html' %}
{% endblock %}

{% block content %}
  <div class="card mb-4">
    <div class="card-header">
      <h5>
        {{ city_item.location.city_name }} | {{ city_item.location.country }}
      </h5>
    </div>
    {% searched_counter city_item.location.city_name request as counter %}
    {% for i in counter.values %}
      {% if not user.is_anonymous %}
        <div class="card-header">
          Searched {{ i }} time(s) by you
        </div>
      {% endif %}
    {% endfor %}
    <div class="card-body">
      <div class="media">
        <img src="https://openweathermap.org/img/w/{{ city_item.weather_description.weather_icon }}.png" alt="icon">
        <div class="media-body">
          <h6 class="card-text">{{ city_item.temperature }}°C <br>
            {{ city_item.weather_description.full_description }}</h6>
          <h6 class="card-text">
            Humidity - {{ city_item.humidity }}% <br>
            Pressure - {{ city_item.pressure }} hPa <br>
            Wind speed - {{ city_item.wind_speed }} meter/sec
          </h6>
        </div>
      </div>
    </div>
    <div class="card-footer text-muted">
      {{ city_item.timestamp|parse_time|date:'Y-m-d | H:i:s' }}
    </div>
    {% if city_item.customers %}
      <div class="card-footer text-muted">
        Users from {{ city_item.location.city_name }}: <br>
        {% for profile in city_item.customers %}
          {% if not forloop.last %}
            <a href="{% url 'siteweather:profile:profile' profile.pk %}">
              {{ profile.first_name }} {{ profile.last_name }}
            </a>,
          {% else %}
            <a href="{% url 'siteweather:profile:profile' profile.pk %}">
              {{ profile.first_name }} {{ profile.last_name }}
            </a>
          {% endif %}
        {% endfor %}
      </div>
    {% endif %}
    {% if city_item.permission %}
      <div class="card-footer text-muted">
        <a href="{% url 'siteweather:delete' city_item.pk %}">
          Delete this block
        </a>
      </div>
    {% endif %}
  </div>
{% endblock %}

{% block time %}
  {% include 'inc/_time.html' %}
{% endblock %}

siteweather/templates/siteweather/delete_confirmation.html
{% extends 'base.html' %}
{% load siteweather_extras %}

{% block title %}
  {{ city_item.city_name }} | {{ city_item.timestamp|date:'m/d/Y' }}
{% endblock %}

{% block sidebar %}
  {% include 'inc/_sidebar.html' %}
{% endblock %}

{% block content %}
  {% if deleted %}
    <div class="btn btn-block disabled btn-danger">
      <strong>
        City block has been successfully deleted
      </strong>
    </div>
  {% else %}
    <div class="card mb-4">
      <div class="card-header">
        <h5>
          {{ city_item.city_name }} | {{ city_item.country }}
        </h5>
      </div>
      <div class="card-body">
        <div class="media">
          <img src="https://openweathermap.org/img/w/{{ city_item.weather_icon }}.png" alt="icon">
          <div class="media-body">
            <h6 class="card-text">{{ city_item.temperature }}°C</h6>
            <h5 class="card-text">{{ city_item.weather_main_description }} </h5>
          </div>
        </div>
      </div>
      <div class="card-footer text-muted">
        {{ city_item.timestamp|parse_time|date:'Y-m-d | H:i:s' }}
      </div>
    </div>
    {% csrf_token %}
    <button type="submit" class="btn-outline-primary btn btn-block" id="submit-delete">
      Delete
    </button>
    <br>
  {% endif %}
{% endblock %}

{% block time %}
  {% include 'inc/_time.html' %}
{% endblock %}

{% block javascript %}
  <script>
    $(document).ready(function () {
      let token = '{{ csrf_token }}';
      $("#submit-delete").click(function (event) {
        event.preventDefault();
        $.ajax({
          headers: {"X-CSRFToken": token},
          type: 'DELETE',
          url: "{% url 'siteweather:delete' city_item.pk %}",
          success: function (response) {
            location.href = {% url 'siteweather:home' %};
            alert(response.message);
          },
          error: function (response) {
            alert(response["responseJSON"]["error"]);
          }
        })
      })
    })
  </script>
{% endblock %}

siteweather/templates/siteweather/find_by.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  Find by city name
{% endblock %}

{% block sidebar %}
  {% include 'inc/_sidebar.html' %}
{% endblock %}

{% block content %}
  <form action="{% url 'siteweather:find_by' %}" method="post" autocomplete="off">
    {% csrf_token %}
    <div class="card mb-4">
      <div class="card-header">
        <div class="form-group">
          <label for="id_city_name">
            City name:
          </label>
          <input type="text" class="form-control" name="city_name"
                 value="{{ data.username }}" required="" id="id_city_name">
          {% if errors %}
            <br>
            {% for error in errors.city_name %}
              <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
              </div>
            {% endfor %}
          {% endif %}
        </div>
        <button type="submit" class="btn-outline-primary btn btn-block">
          Find
        </button>
      </div>
    </div>
  </form>
{% endblock %}

{% block time %}
  {% include 'inc/_time.html' %}
{% endblock %}

{% block javascript %}
{% endblock %}

siteweather/templates/siteweather/home.html
{% extends 'base.html' %}
{% load siteweather_extras %}

{% block title %}
  Home
{% endblock %}

{% block sidebar %}
  {% include 'inc/_sidebar.html' %}
{% endblock %}

{% block pagination %}
  {% include 'inc/_pagination.html' %}
{% endblock %}

{% block content %}
  {% if not results %}
    <div class="card card-body text-muted">
      <strong>
        Can not find any {{ request.GET.dict.city_name_filter|correct_name }} data. <br>
        Try to search by city name.
        {% if request.GET.dict.date_filter %}
          for the <br>{{ request.GET.dict.date_filter }}
        {% endif %}
      </strong>
    </div>
    <br>
  {% endif %}
  {% for item in results %}
    <div class="card mb-4">
      <div class="card-header">
        <h5>
          {{ item.location.city_name }} | {{ item.location.country }}
        </h5>
      </div>
      <div class="card-body">
        <div class="media">
          <img src="https://openweathermap.org/img/w/{{ item.weather_description.weather_icon }}.png" alt="icon">
          <div class="media-body">
            <h6 class="card-text">{{ item.temperature }}°C</h6>
            <h5 class="card-text">{{ item.weather_description.short_description }}
            </h5>
            <a href="{% url 'siteweather:view_city' item.id %}" class="btn btn-outline-primary btn-block">Read more</a>
          </div>
        </div>
      </div>
      <div class="card-footer text-muted">
        {{ item.timestamp|parse_time|date:'Y-m-d | H:i:s' }}
      </div>
    </div>
  {% endfor %}
  <div class="card card-header" id="content">
    <div class="text-muted">
      Filter
    </div>
    <form action="{% url 'siteweather:home' %}" method="get" autocomplete="off">
      <label for="id_city_name_filter">
        City:
        <input type="search" class="form-control" name="city_name_filter"
               id="id_city_name_filter" value="{{ request.GET.dict.city_name_filter|correct_name }}">
      </label>
      <label for="id_date_filter">
        Date:
        <input type="date" class="form-control" name="date_filter"
               id="id_date_filter" value="{{ request.GET.dict.date_filter }}">
      </label>
      <button type="submit" class="btn-outline-primary btn btn-block">
        Filter
      </button>
      <br>
    </form>
  </div>

{% endblock %}

{% block time %}
  {% include 'inc/_time.html' %}
{% endblock %}

{% block javascript %}
  <script>
    $(document).ready(function () {

    })
  </script>
{% endblock %}

siteweather/templates/siteweather/registered_users.html
{% extends 'base.html' %}
{% load siteweather_extras %}

{% block title %}
  Registered users
{% endblock %}

{% block sidebar %}
  {% include 'inc/_sidebar.html' %}
{% endblock %}

{% block pagination %}
  {% if perms.siteweather.see_users or user.is_superuser or user.role == 'Premium' %}
    {% include 'inc/_users_pagination.html' %}
  {% endif %}
{% endblock %}

{% block content %}
  {% if perms.siteweather.see_users or user.is_superuser or user.role == 'Premium' %}
    {% if not results %}
      {% if user.is_authenticated %}
        <div class="btn btn-block disabled btn-success">
          <strong>
            Can not find any user
            {% if request.GET.dict.city_name_filter %}
              from {{ request.GET.dict.city_name_filter|correct_name }}
            {% endif %}
            {% if request.GET.dict.first_name_filter %}
              <br>
              whose name starts with {{ request.GET.dict.first_name_filter|correct_name }}
              {{ request.GET.dict.last_name_filter|correct_name }}
            {% elif request.GET.dict.last_name_filter|correct_name %}
              <br>
              whose surname starts with {{ request.GET.dict.last_name_filter|correct_name }}
            {% endif %}
          </strong>
        </div>
      {% endif %}
    {% endif %}
    <div class="list-group">
      {% for person in results %}
        <a href="{% url 'siteweather:profile:profile' person.pk %}" class="list-group-item-action list-group-item">
          {{ person.first_name }} {{ person.last_name }}
          {% if person.user_city %}
            | {{ person.user_city }}
          {% endif %}
        </a>
      {% endfor %}
    </div>
    <br>
    <form action="{% url 'siteweather:users_list' %}" method="get" autocomplete="off">
      <label for="id_city_name_filter">
        City:
        <input type="search" class="form-control" name="city_name_filter"
               id="id_city_name_filter" value="{{ request.GET.dict.city_name_filter|correct_name }}">
      </label>
      <label for="id_first_name_filter">
        First name:
        <input type="search" class="form-control" name="first_name_filter"
               id="id_first_name_filter" value="{{ request.GET.dict.first_name_filter|correct_name }}">
      </label>
      <label for="id_last_name_filter">
        Surname:
        <input type="search" class="form-control" name="last_name_filter"
               id="id_last_ame_filter" value="{{ request.GET.dict.last_name_filter|correct_name }}">
      </label>
      <button type="submit" class="btn-outline-primary btn btn-block">
        Filter
      </button>
      <br>
    </form>
  {% else %}
    <div class="btn btn-block disabled btn-danger">
      <strong>
        You are not authorized to view this page.
      </strong>
    </div>
    <br>
  {% endif %}
{% endblock %}

{% block time %}
  {% include 'inc/_time.html' %}
{% endblock %}

siteweather/templates/siteweather/site_settings.html
{% extends 'base.html' %}

{% block sidebar %}
  {% include 'inc/_sidebar.html' %}
{% endblock %}

{% block time %}
  {% include 'inc/_time.html' %}
{% endblock %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    {% load tz %}
    {% get_current_timezone as TIME_ZONE %}
    <label for="timezone">
      Time zone:
      <select name="timezone" class="form-control">
        {% for tz in timezones %}
          <option value="{{ tz }}" {% if tz == TIME_ZONE %}
                  selected {% endif %}>{{ tz }}</option>
        {% endfor %}
      </select>
      <br>
      <button type="submit" class="btn-outline-primary btn btn-block">
        Set
      </button>
    </label>
  </form>
{% endblock %}