siteweather/urls.py
from django.urls import path, include

from .views import *

app_name = 'siteweather'

siteweather_urls = [
    path('', Home.as_view(), name='home'),
    path('<int:pk>/', ViewCity.as_view(), name='view_city'),
    path('city_block/<int:pk>/', DeleteCityBlock.as_view(), name='delete'),
    path('find_by/', FindCity.as_view(), name='find_by'),
    path('registered_users/', UsersList.as_view(), name='users_list'),
    path('site_settings/', PersonalSiteSettingsAPIView.as_view(), name='site_settings'),
]

urlpatterns = [
    path('', include('siteweather.authentication.urls')),
    path('', include('siteweather.profile.urls')),
    path('siteweather/', include(siteweather_urls)),
]

task/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from siteweather.views import schema_view
from task import settings
from siteweather.authentication.views import AdminLogoutView


urlpatterns = [
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('docs/', schema_view, name="docs"),
    path('admin/logout/', AdminLogoutView.as_view()),
    path('admin/', admin.site.urls),
    path('', include('siteweather.urls', namespace='siteweather')),
    path('api-auth/', include('rest_framework.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/inc/_last_registered_users.html
{% for user in last_users %}
  <a href="{% url 'siteweather:profile:profile' user.pk %}">
    {{ user.first_name }} {{ user.last_name }} <br>
  </a>
{% endfor %}

templates/inc/_pagination.html
<nav aria-label="...">
  <ul class="pagination">
    {% if previous %}
      <li class="page-item">
        <a class="page-link" href="{{ previous }}">
          Previous elements
        </a>
      </li>
    {% endif %}
    {% if next %}
      <li class="page-item">
        <a class="page-link" href="{{ next }}">
          Next elements
        </a>
      </li>
    {% endif %}
  </ul>
</nav>

templates/inc/_sidebar.html
<div class="list-group">
  <a href="{% url 'siteweather:home' %}" class="list-group-item list-group-item-action">
    List
  </a>
  <a href="{% url 'siteweather:find_by' %}" class="list-group-item list-group-item-action">
    Find by city
  </a>
  {% if not user.is_authenticated %}
    <a href="{% url 'siteweather:auth:register' %}" class="list-group-item list-group-item-action">
      Register
    </a>
    <a href="{% url 'siteweather:auth:login' %}" class="list-group-item list-group-item-action">
      Login
    </a>
  {% else %}
    <a href="{% url 'siteweather:profile:profile' user.pk %}"
       class="list-group-item list-group-item-action border-top-0">
      Profile
    </a>
    {% if user.role == 'Premium' or user.is_superuser %}
      <a href="{% url 'siteweather:users_list' %}" class="list-group-item list-group-item-action border-top-0">
        List of users
      </a>
    {% endif %}
    <button class="list-group-item list-group-item-action border-top-0" id="logout-button"><a href=""
                                                                                              class=""> </a>

      Logout
    </button>
  {% endif %}
  <a href="{% url 'siteweather:site_settings' %}" class="list-group-item list-group-item-action border-top-0">
    Personal website settings
  </a>
</div>
<br>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>

{% block javascript %}
  <script>
    $(document).ready(function () {
      let token = '{{ csrf_token }}';
      $("#logout-button").click(function (event) {
        event.preventDefault();
        $.ajax({
          type: 'POST',
          url: '{% url 'siteweather:auth:logout' %}',
          headers: {"X-CSRFToken": token},
          success: function () {
            location.href = '{% url 'siteweather:home' %}';
          },
          failure: function (response) {
            alert(response["responseJSON"]["error"]);
          }
        })
      })
    })
  </script>
{% endblock %}

templates/inc/_time.html
<div class="card mb-4">
  <div class="card-footer text-muted border-top-0">
    {% now "l, \t\h\e jS \o\f F" %}
    <br>
    {% load tz %}
    {% get_current_timezone as TIME_ZONE %}
    {% now "H:i" %} | {{ TIME_ZONE }}
  </div>
</div>

templates/inc/_users_pagination.html
<nav aria-label="...">
  <ul class="pagination">
    {% if previous %}
      <li class="page-item">
        <a class="page-link" href="{{ previous }}">
          Previous users
        </a>
      </li>
    {% endif %}
    {% if next %}
      <li class="page-item">
        <a class="page-link" href="{{ next }}">
          Next users
        </a>
      </li>
    {% endif %}
  </ul>
</nav>